name: CI

on: [push]

jobs:
  test:
    strategy:
      matrix:
        node: [12, 13]
    name: Test Node v${{ matrix.node }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node
      - name: Install npm packages
        run: npm i
      - name: Lint
        run: npm run lint
      - name: Setup cc-test-reporter
        if: github.repository != 'anchan828/nest-lerna-template'
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build
      - name: Test monorepo packages
        run: |
          npm test
          npx ts-node scripts/merge-coverage.ts
      - name: Report coverage
        if: github.repository != 'anchan828/nest-lerna-template'
        run: ./cc-test-reporter after-build -r ${{ secrets.CC_TEST_REPORTER_ID }} --coverage-input-type lcov
